import React from 'react';

/**
 * Strips leading/trailing empty paragraphs a rich-text editor leaves behind
 * from stray extra Enter presses — `<p></p>`, and the equivalent
 * `<p><br></p>` / `<p>&nbsp;</p>` TipTap and other editors also emit for an
 * "empty" line. These carry no content but still take up a paragraph's
 * default vertical margin, so left in they show as blank gaps at the start
 * or end of an otherwise correctly-rendered block. Only leading/trailing
 * empties are removed — one in the middle of real content stays, since that
 * is a deliberate blank line the person writing it put there.
 */
const stripEdgeEmptyParagraphs = (html) => {
  const emptyParagraph = /^<p>(?:\s|&nbsp;|<br\s*\/?>)*<\/p>$/i;
  const paragraphs = html.match(/<p(?:\s[^>]*)?>[\s\S]*?<\/p>|<[a-z][^>]*>[\s\S]*?<\/[a-z]+>/gi);
  if (!paragraphs || paragraphs.length <= 1) return html;

  let start = 0;
  let end = paragraphs.length;
  while (start < end && emptyParagraph.test(paragraphs[start].trim())) start++;
  while (end > start && emptyParagraph.test(paragraphs[end - 1].trim())) end--;

  return paragraphs.slice(start, end).join('');
};

/**
 * Safely renders rich text (HTML generated by TipTap) or fallback plain text
 * with proper line breaks.
 */
export const renderRichText = (content, style = {}) => {
  if (!content) return null;
  const isHtml = /<[a-z][\s\S]*>/i.test(content);
  if (isHtml) {
    return (
      <div
        className="rich-text-display"
        style={{ fontSize: '11px', color: '#444', marginTop: '3px', ...style }}
        dangerouslySetInnerHTML={{ __html: stripEdgeEmptyParagraphs(content) }}
      />
    );
  }
  return (
    <div
      className="rich-text-display"
      style={{ fontSize: '11px', color: '#444', whiteSpace: 'pre-line', marginTop: '3px', ...style }}
    >
      {content}
    </div>
  );
};

export default renderRichText;
