import React from 'react';

/**
 * Safely renders rich text (HTML generated by TipTap) or fallback plain text
 * with proper line breaks.
 */
export const renderRichText = (content, style = {}) => {
  if (!content) return null;
  const isHtml = /<[a-z][\s\S]*>/i.test(content);
  if (isHtml) {
    return (
      <div
        className="rich-text-display"
        style={{ fontSize: '11px', color: '#444', marginTop: '3px', ...style }}
        dangerouslySetInnerHTML={{ __html: content }}
      />
    );
  }
  return (
    <div
      className="rich-text-display"
      style={{ fontSize: '11px', color: '#444', whiteSpace: 'pre-line', marginTop: '3px', ...style }}
    >
      {content}
    </div>
  );
};

export default renderRichText;
