<?php

namespace App\Models;

use App\Traits\Archivable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles, Archivable;

    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'manager_id',
        'phone',
        'is_active',
        'is_archived',
        'archived_at',
        'archived_by',
        'archive_reason',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'password'          => 'hashed',
        'is_active'          => 'boolean',
        'is_archived'       => 'boolean',
        'archived_at'       => 'datetime',
    ];

    /**
     * Relationship: Get the manager assigned to this salesman.
     * Constraint: FK manager_id -> users.id (nullable)
     */
    public function manager(): BelongsTo
    {
        return $this->belongsTo(User::class, 'manager_id');
    }

    /**
     * Relationship: Get the salesmen managed by this manager.
     * Constraint: FK manager_id -> users.id
     */
    public function salesmen(): HasMany
    {
        return $this->hasMany(User::class, 'manager_id');
    }

    /**
     * Relationship: Customers created by this user/salesman.
     */
    public function createdCustomers(): HasMany
    {
        return $this->hasMany(Customer::class, 'created_by');
    }

    /**
     * Relationship: User's notification settings.
     */
    public function notificationSetting(): HasOne
    {
        return $this->hasOne(NotificationSetting::class);
    }

    /**
     * Relationship: Notifications for this user.
     */
    public function notifications(): HasMany
    {
        return $this->hasMany(Notification::class);
    }

    /**
     * Relationship: Audit logs generated by this user.
     */
    public function auditLogs(): HasMany
    {
        return $this->hasMany(AuditLog::class);
    }
}
